service: reto-tecnico
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-auto-swagger

provider:
  name: aws
  environment:
    SWAPI_BASE_URL: https://swapi.py4e.com/api
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:PutItem'
          Resource: '*'
        - Effect: Allow
          Action: 'dynamodb:Scan'
          Resource: '*'

functions:
  cmd:
    handler: ./src/handlers/save-data.main
    events:
      - http:
          path: /
          method: post
          bodyType: IPeople
  qry:
    handler: ./src/handlers/get-data.main
    events:
      - http:
          path: /
          method: get

resources:
  Resources:
    charactersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: characters-table
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1