export const mapFields: { [key: string]: string } = {
    "name": "nombre",
    "height": "altura",
    "mass": "peso",
    "hair_color": "color_cabello",
    "skin_color": "color_piel",
    "eye_color": "color_ojos",
    "birth_year": "año_nacimiento",
    "gender": "genero",
    "homeworld": "planeta_origen",
    "films": "peliculas",
    "species": "especie",
    "vehicles": "vehiculos",
    "starships": "naves_estelares",
    "rotation_period": "periodo_rotacion",
    "orbital_period": "periodo_orbital",
    "diameter": "diametro",
    "climate": "clima",
    "gravity": "gravedad",
    "terrain": "terreno",
    "surface_water": "agua_superficie",
    "population": "poblacion",
    "residents": "residentes",
    "created": "creado",
    "edited": "editado",
    "url": "url"
};